import torch
from torch.utils.data import DataLoader, Dataset
import json
import numpy as np
import logging
import pickle
import math
import dgl
from sklearn.model_selection import train_test_split

def load_pickle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

def load_data(args):
    train = SynData(args, data_type='train')
    train_loader = DataLoader(train, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))
    valid = SynData(args, data_type='valid')
    valid_loader = DataLoader(valid, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))
    test = SynData(args, data_type='test')
    test_loader = DataLoader(test, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))

    return train_loader, valid_loader, test_loader

def load_data_ddi(args):
    train = DDIData(args, data_type='train')
    train_loader = DataLoader(train, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))
    valid = DDIData(args, data_type='valid')
    valid_loader = DataLoader(valid, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))
    test = DDIData(args, data_type='test')
    test_loader = DataLoader(test, batch_size=args.batch_size, shuffle=True, generator=torch.Generator().manual_seed(2024))

    return train_loader, valid_loader, test_loader

class SynData(Dataset):
    def __init__(self, args, data_type='train') -> None:
        self.args = args
        self.data_type = data_type
        print(f'processing {data_type} dataset...')
        
        self._read_samples()

    def __len__(self):
        l = len(self.samples)
        return l
    
    def _read_samples(self):
        self.samples = []
        self.embed_dict = {}

        drug_embed = np.load(f'ckpts/llms/{self.args.llm}/drug_embed_all.npy')
        cell_embed = np.load(f'ckpts/llms/{self.args.llm}/cell_embed_all.npy')
        
        # loading bge embeddings, which are generated by the same llm as the descriptions, and thus may be more consistent with the description embeddings.
        # drug_embed = np.load(f'ckpts/llms/{self.args.llm}/drug_embed_bge.npy')
        # cell_embed = np.load(f'ckpts/llms/{self.args.llm}/cell_embed_bge.npy')
        
        # random embeddings for ablation study
        # cell_embed = np.random.rand(cell_embed.shape[0], cell_embed.shape[1])
        # print('random embeddings loaded.')

        with open(f'ckpts/llms/{self.args.llm}/drug_map.tsv', 'r') as f:
            # f.readline()
            for idx, line in enumerate(f):
                did, dname = line.strip().split('\t')
                self.embed_dict[dname.strip().lower()] = drug_embed[int(did)]

        with open(f'ckpts/llms/{self.args.llm}/cell_map.tsv', 'r') as f:
            # f.readline()
            for idx, line in enumerate(f):
                cid, cname = line.strip().split('\t')
                self.embed_dict[cname.strip().lower()] = cell_embed[int(cid)]

        with open(f'datasets/{self.args.dataset}/{self.args.setting}/{self.data_type}.txt', 'r') as f:
            print(f'datasets/{self.args.dataset}/{self.args.setting}/{self.data_type}.txt')
            for line in f:
                infos = line.strip().split('\t')
                d1, d2, cell, label = int(infos[1]), int(infos[3]), int(infos[5]), int(infos[6])
                d1_embed = self.embed_dict[infos[0].strip().lower()]
                d2_embed = self.embed_dict[infos[2].strip().lower()]
                c_embed = self.embed_dict[infos[4].strip().lower()]

                self.samples.append([d1, d2, cell, d1_embed, d2_embed, c_embed, label])

    def __getitem__(self, index):
        d1, d2, cell, d1_embed, d2_embed, c_embed, label = self.samples[index]

        return d1, d2, cell, d1_embed, d2_embed, c_embed, label